/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OOrgSlugRouteRouteImport } from './routes/o/$orgSlug/route'
import { Route as OOrgSlugIndexRouteImport } from './routes/o/$orgSlug/index'
import { Route as OOrgSlugAssetsRouteImport } from './routes/o/$orgSlug/assets'
import { Route as OOrgSlugAuditRouteImport } from './routes/o/$orgSlug/audit'
import { Route as OOrgSlugCustomersRouteImport } from './routes/o/$orgSlug/customers'
import { Route as OOrgSlugDispatchRouteImport } from './routes/o/$orgSlug/dispatch'
import { Route as OOrgSlugPlatformRouteImport } from './routes/o/$orgSlug/platform'
import { Route as OOrgSlugReportsRouteImport } from './routes/o/$orgSlug/reports'
import { Route as OOrgSlugScheduleRouteImport } from './routes/o/$orgSlug/schedule'
import { Route as OOrgSlugSettingsRouteImport } from './routes/o/$orgSlug/settings'
import { Route as OOrgSlugSitesRouteImport } from './routes/o/$orgSlug/sites'
import { Route as OOrgSlugTeamRouteImport } from './routes/o/$orgSlug/team'
import { Route as OOrgSlugWorkOrdersRouteImport } from './routes/o/$orgSlug/work-orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugRouteRoute = OOrgSlugRouteRouteImport.update({
  id: '/o/$orgSlug',
  path: '/o/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugIndexRoute = OOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugAssetsRoute = OOrgSlugAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugAuditRoute = OOrgSlugAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugCustomersRoute = OOrgSlugCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugDispatchRoute = OOrgSlugDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugPlatformRoute = OOrgSlugPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugReportsRoute = OOrgSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugScheduleRoute = OOrgSlugScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugSettingsRoute = OOrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugSitesRoute = OOrgSlugSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugTeamRoute = OOrgSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)
const OOrgSlugWorkOrdersRoute = OOrgSlugWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => OOrgSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/o/$orgSlug': typeof OOrgSlugRouteRouteWithChildren
  '/o/$orgSlug/assets': typeof OOrgSlugAssetsRoute
  '/o/$orgSlug/audit': typeof OOrgSlugAuditRoute
  '/o/$orgSlug/customers': typeof OOrgSlugCustomersRoute
  '/o/$orgSlug/dispatch': typeof OOrgSlugDispatchRoute
  '/o/$orgSlug/platform': typeof OOrgSlugPlatformRoute
  '/o/$orgSlug/reports': typeof OOrgSlugReportsRoute
  '/o/$orgSlug/schedule': typeof OOrgSlugScheduleRoute
  '/o/$orgSlug/settings': typeof OOrgSlugSettingsRoute
  '/o/$orgSlug/sites': typeof OOrgSlugSitesRoute
  '/o/$orgSlug/team': typeof OOrgSlugTeamRoute
  '/o/$orgSlug/work-orders': typeof OOrgSlugWorkOrdersRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o/$orgSlug/assets': typeof OOrgSlugAssetsRoute
  '/o/$orgSlug/audit': typeof OOrgSlugAuditRoute
  '/o/$orgSlug/customers': typeof OOrgSlugCustomersRoute
  '/o/$orgSlug/dispatch': typeof OOrgSlugDispatchRoute
  '/o/$orgSlug/platform': typeof OOrgSlugPlatformRoute
  '/o/$orgSlug/reports': typeof OOrgSlugReportsRoute
  '/o/$orgSlug/schedule': typeof OOrgSlugScheduleRoute
  '/o/$orgSlug/settings': typeof OOrgSlugSettingsRoute
  '/o/$orgSlug/sites': typeof OOrgSlugSitesRoute
  '/o/$orgSlug/team': typeof OOrgSlugTeamRoute
  '/o/$orgSlug/work-orders': typeof OOrgSlugWorkOrdersRoute
  '/o/$orgSlug': typeof OOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/o/$orgSlug': typeof OOrgSlugRouteRouteWithChildren
  '/o/$orgSlug/assets': typeof OOrgSlugAssetsRoute
  '/o/$orgSlug/audit': typeof OOrgSlugAuditRoute
  '/o/$orgSlug/customers': typeof OOrgSlugCustomersRoute
  '/o/$orgSlug/dispatch': typeof OOrgSlugDispatchRoute
  '/o/$orgSlug/platform': typeof OOrgSlugPlatformRoute
  '/o/$orgSlug/reports': typeof OOrgSlugReportsRoute
  '/o/$orgSlug/schedule': typeof OOrgSlugScheduleRoute
  '/o/$orgSlug/settings': typeof OOrgSlugSettingsRoute
  '/o/$orgSlug/sites': typeof OOrgSlugSitesRoute
  '/o/$orgSlug/team': typeof OOrgSlugTeamRoute
  '/o/$orgSlug/work-orders': typeof OOrgSlugWorkOrdersRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/o/$orgSlug'
    | '/o/$orgSlug/assets'
    | '/o/$orgSlug/audit'
    | '/o/$orgSlug/customers'
    | '/o/$orgSlug/dispatch'
    | '/o/$orgSlug/platform'
    | '/o/$orgSlug/reports'
    | '/o/$orgSlug/schedule'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/sites'
    | '/o/$orgSlug/team'
    | '/o/$orgSlug/work-orders'
    | '/o/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/o/$orgSlug/assets'
    | '/o/$orgSlug/audit'
    | '/o/$orgSlug/customers'
    | '/o/$orgSlug/dispatch'
    | '/o/$orgSlug/platform'
    | '/o/$orgSlug/reports'
    | '/o/$orgSlug/schedule'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/sites'
    | '/o/$orgSlug/team'
    | '/o/$orgSlug/work-orders'
    | '/o/$orgSlug'
  id:
    | '__root__'
    | '/'
    | '/o/$orgSlug'
    | '/o/$orgSlug/assets'
    | '/o/$orgSlug/audit'
    | '/o/$orgSlug/customers'
    | '/o/$orgSlug/dispatch'
    | '/o/$orgSlug/platform'
    | '/o/$orgSlug/reports'
    | '/o/$orgSlug/schedule'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/sites'
    | '/o/$orgSlug/team'
    | '/o/$orgSlug/work-orders'
    | '/o/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OOrgSlugRouteRoute: typeof OOrgSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug': {
      id: '/o/$orgSlug'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof OOrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/': {
      id: '/o/$orgSlug/'
      path: '/'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof OOrgSlugIndexRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/assets': {
      id: '/o/$orgSlug/assets'
      path: '/assets'
      fullPath: '/o/$orgSlug/assets'
      preLoaderRoute: typeof OOrgSlugAssetsRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/audit': {
      id: '/o/$orgSlug/audit'
      path: '/audit'
      fullPath: '/o/$orgSlug/audit'
      preLoaderRoute: typeof OOrgSlugAuditRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/customers': {
      id: '/o/$orgSlug/customers'
      path: '/customers'
      fullPath: '/o/$orgSlug/customers'
      preLoaderRoute: typeof OOrgSlugCustomersRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/dispatch': {
      id: '/o/$orgSlug/dispatch'
      path: '/dispatch'
      fullPath: '/o/$orgSlug/dispatch'
      preLoaderRoute: typeof OOrgSlugDispatchRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/platform': {
      id: '/o/$orgSlug/platform'
      path: '/platform'
      fullPath: '/o/$orgSlug/platform'
      preLoaderRoute: typeof OOrgSlugPlatformRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/reports': {
      id: '/o/$orgSlug/reports'
      path: '/reports'
      fullPath: '/o/$orgSlug/reports'
      preLoaderRoute: typeof OOrgSlugReportsRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/schedule': {
      id: '/o/$orgSlug/schedule'
      path: '/schedule'
      fullPath: '/o/$orgSlug/schedule'
      preLoaderRoute: typeof OOrgSlugScheduleRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/settings': {
      id: '/o/$orgSlug/settings'
      path: '/settings'
      fullPath: '/o/$orgSlug/settings'
      preLoaderRoute: typeof OOrgSlugSettingsRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/sites': {
      id: '/o/$orgSlug/sites'
      path: '/sites'
      fullPath: '/o/$orgSlug/sites'
      preLoaderRoute: typeof OOrgSlugSitesRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/team': {
      id: '/o/$orgSlug/team'
      path: '/team'
      fullPath: '/o/$orgSlug/team'
      preLoaderRoute: typeof OOrgSlugTeamRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
    '/o/$orgSlug/work-orders': {
      id: '/o/$orgSlug/work-orders'
      path: '/work-orders'
      fullPath: '/o/$orgSlug/work-orders'
      preLoaderRoute: typeof OOrgSlugWorkOrdersRouteImport
      parentRoute: typeof OOrgSlugRouteRoute
    }
  }
}

interface OOrgSlugRouteRouteChildren {
  OOrgSlugAssetsRoute: typeof OOrgSlugAssetsRoute
  OOrgSlugAuditRoute: typeof OOrgSlugAuditRoute
  OOrgSlugCustomersRoute: typeof OOrgSlugCustomersRoute
  OOrgSlugDispatchRoute: typeof OOrgSlugDispatchRoute
  OOrgSlugPlatformRoute: typeof OOrgSlugPlatformRoute
  OOrgSlugReportsRoute: typeof OOrgSlugReportsRoute
  OOrgSlugScheduleRoute: typeof OOrgSlugScheduleRoute
  OOrgSlugSettingsRoute: typeof OOrgSlugSettingsRoute
  OOrgSlugSitesRoute: typeof OOrgSlugSitesRoute
  OOrgSlugTeamRoute: typeof OOrgSlugTeamRoute
  OOrgSlugWorkOrdersRoute: typeof OOrgSlugWorkOrdersRoute
  OOrgSlugIndexRoute: typeof OOrgSlugIndexRoute
}

const OOrgSlugRouteRouteChildren: OOrgSlugRouteRouteChildren = {
  OOrgSlugAssetsRoute: OOrgSlugAssetsRoute,
  OOrgSlugAuditRoute: OOrgSlugAuditRoute,
  OOrgSlugCustomersRoute: OOrgSlugCustomersRoute,
  OOrgSlugDispatchRoute: OOrgSlugDispatchRoute,
  OOrgSlugPlatformRoute: OOrgSlugPlatformRoute,
  OOrgSlugReportsRoute: OOrgSlugReportsRoute,
  OOrgSlugScheduleRoute: OOrgSlugScheduleRoute,
  OOrgSlugSettingsRoute: OOrgSlugSettingsRoute,
  OOrgSlugSitesRoute: OOrgSlugSitesRoute,
  OOrgSlugTeamRoute: OOrgSlugTeamRoute,
  OOrgSlugWorkOrdersRoute: OOrgSlugWorkOrdersRoute,
  OOrgSlugIndexRoute: OOrgSlugIndexRoute,
}

const OOrgSlugRouteRouteWithChildren = OOrgSlugRouteRoute._addFileChildren(
  OOrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OOrgSlugRouteRoute: OOrgSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
