#!/usr/bin/env bash
# Runs the engineering proofs that back docs/evidence/ledger.md and writes a
# timestamped, commit-stamped report. Each proof is an automated test; this
# script only orchestrates and records outcomes.
set -uo pipefail

cd "$(dirname "$0")/.."
export GOTOOLCHAIN=go1.27.1
report=docs/evidence/proofs-report.md
tmp=$(mktemp)
commit=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
dirty=$(git diff --quiet 2>/dev/null || echo " (uncommitted changes)")
pass=0; fail=0

run() { # name, ledger property, command...
  local name="$1" property="$2"; shift 2
  local start end status
  start=$(date +%s)
  if "$@" >"$tmp.log" 2>&1; then status="✅ pass"; pass=$((pass+1)); else status="❌ fail"; fail=$((fail+1)); fi
  end=$(date +%s)
  printf '| %s | %s | %s | %ss |\n' "$name" "$property" "$status" "$((end-start))" >>"$tmp"
  printf '  %-58s %s\n' "$name" "$status"
  [[ $status == "❌ fail" ]] && tail -20 "$tmp.log" | sed 's/^/      /'
  return 0
}

go_proof() { go test -tags integration -count=1 -run "$1" "$2"; }

echo "Running OpsGrid engineering proofs @ ${commit}${dirty}"
: >"$tmp"
run "Tenant context is transaction-local (pooled connection reuse)" "RLS fail-closed" \
  go_proof 'TestTenantContextIsTransactionLocal$' ./internal/platform/database/
run "Missing tenant context is rejected before SQL runs" "RLS fail-closed" \
  go_proof 'TestInTenantTxRequiresOrganization$' ./internal/platform/database/
run "RLS policy template isolates tenants; denies owner; fails closed" "Tenant confidentiality" \
  go_proof 'TestRLSPolicyTemplateFailsClosed$' ./internal/platform/database/
run "Runtime roles: no superuser/BYPASSRLS/DDL; guard-rail timeouts" "Runtime role hardening" \
  go_proof 'TestRuntimeRolesAreHardened$' ./internal/platform/database/
run "Serialization failures retried; other errors not" "Transactional safety" \
  go_proof 'TestRetriesSerializationFailures$' ./internal/platform/database/
run "Graceful shutdown drains in-flight requests" "Operational readiness" \
  go test -count=1 -run 'TestServeDrainsInFlightRequests$' ./internal/platform/httpx/
run "Internal errors never leak database text" "Security" \
  go test -count=1 -run 'TestUntypedErrorNeverLeaksText$|TestInternalTypedErrorAlsoHidesMessage$' ./internal/platform/httpx/
run "CSRF: cross-site unsafe requests rejected" "Security" \
  go test -count=1 -run 'TestCSRF$' ./internal/platform/httpx/
run "Secrets redacted from logs" "Security" \
  go test -count=1 -run 'TestRedactsSensitiveKeys$' ./internal/platform/telemetry/
run "Migrations well-formed and contiguous" "Migration safety" \
  go test -count=1 ./db/
run "Design tokens meet WCAG 2.2 AA contrast (light + dark)" "Accessibility" \
  pnpm --filter @opsgrid/web exec vitest run --project unit src/design/tokens.test.ts
run "Shell: focus management, skip link, axe clean" "Accessibility" \
  pnpm --filter @opsgrid/web exec vitest run --project unit src/app/shell.test.tsx

{
  echo "# Proofs report"
  echo
  echo "Generated by \`make proofs\` on $(date -u +%Y-%m-%dT%H:%M:%SZ) at commit \`${commit}\`${dirty}."
  echo
  echo "**${pass} passed, ${fail} failed.**"
  echo
  echo "| Proof | Ledger property | Result | Duration |"
  echo "|---|---|---|---|"
  cat "$tmp"
} >"$report"
rm -f "$tmp" "$tmp.log"
echo "Wrote $report (${pass} passed, ${fail} failed)"
[[ $fail -eq 0 ]]
